const STORES=['Superstore','No Frills','Walmart','Safeway','Sobeys','Costco'];
const BANNERS={Superstore:['real canadian superstore','superstore','rcss'],'No Frills':['no frills','nofrills'],Walmart:['walmart'],Safeway:['safeway'],Sobeys:['sobeys']};
const LOCAL={
  Superstore:{milk:{price:6.35,notes:'Beatrice 1% 4L · Spruce Grove Superstore 1565'},eggs:{price:4.18,notes:'No Name large 12'},vector:{price:8.49,notes:'Kellogg’s Vector original'},bubly:{price:5.99,notes:'Bubly 12 pack'}},
  'No Frills':{milk:{price:6.35,notes:'Beatrice 1% 4L · Steve’s No Frills 3628'},eggs:{price:4.18,notes:'No Name large 12'},bubly:{price:6.50,notes:'Bubly 12 pack'}}
};
const Q={milk:'1% milk 4L',eggs:'large eggs 12',yogurt:'plain Greek yogurt 1 kg',eggwhites:'egg whites 500 g',vector:'Kelloggs Vector cereal 400 g',ricekrispies:'Kelloggs Rice Krispies cereal',chicken:'boneless skinless chicken breast',bananas:'bananas',pork:'pork tenderloin',bubly:'Bubly 12 pack',wheatthins:'Wheat Thins Original crackers',ritz:'Ritz crackers',peanut:'Kraft smooth peanut butter',silk:'Silk hazelnut coffee creamer',cheese:'marble cheese',bread:'whole wheat bread',romaine:'romaine hearts',carrots:'carrots',peppers:'bell peppers',oranges:'oranges',grapes:'red seedless grapes',blueberries:'blueberries',potatoes:'baby potatoes',butter:'butter 454 g',clif:"Clif Builder's protein bars",kd:'Kraft Dinner original macaroni and cheese',burgers:'beef burger patties'};
const LABEL={milk:'1% milk 4L',eggs:'large eggs 12',yogurt:'plain Greek yogurt 1 kg',eggwhites:'egg whites 500 g',vector:'Vector cereal 400 g',ricekrispies:'Rice Krispies cereal',chicken:'boneless skinless chicken breast',bananas:'bananas',pork:'pork tenderloin',bubly:'Bubly 12 pack',wheatthins:'Wheat Thins Original',ritz:'Ritz crackers',peanut:'Kraft smooth peanut butter',silk:'Silk hazelnut coffee creamer',cheese:'marble cheese',bread:'whole wheat bread',romaine:'romaine hearts',carrots:'carrots',peppers:'bell peppers',oranges:'oranges',grapes:'red seedless grapes',blueberries:'blueberries',potatoes:'baby potatoes',butter:'butter 454 g',clif:"Clif Builder's protein bars",kd:'Kraft Dinner',burgers:'frozen hamburger patties'};
const UNIT100G=new Set(['ricekrispies','wheatthins','ritz','peanut','cheese','bread','blueberries','potatoes','kd','burgers']);
const UNIT100ML=new Set(['silk']);
const UNITEACH=new Set(['clif']);
const WEIGHTED=new Set(['chicken','bananas','pork','carrots','oranges','grapes']);

function clean(s){return String(s||'').toLowerCase().replace(/[^a-z0-9%]+/g,' ')}
function bannerOf(r){return clean(r?.banner?.value||r?.provider?.value||'')}
function sizeGrams(s){s=clean(s);let m=s.match(/([0-9.]+)\s*kg\b/);if(m)return +m[1]*1000;m=s.match(/([0-9.]+)\s*g\b/);if(m)return +m[1];return null}
function sizeMl(s){s=clean(s);let m=s.match(/([0-9.]+)\s*l\b/);if(m)return +m[1]*1000;m=s.match(/([0-9.]+)\s*ml\b/);if(m)return +m[1];return null}
function countUnits(s){s=clean(s);let m=s.match(/([0-9]+)\s*(?:pack|pk|count|ct|ea|bars?|patties|pieces?|units?)\b/);return m?+m[1]:null}
function compPrice(r){let c=r?.comparison_unit_price;if(!c||!Number.isFinite(+c.price)||!c.per)return null;return{price:+c.price,per:clean(c.per)}}
function unitKg(r){let c=compPrice(r);if(c){if(/100\s*g/.test(c.per))return c.price*10;if(/kg/.test(c.per))return c.price;}let g=sizeGrams([r?.size,r?.product_name].filter(Boolean).join(' '));return g&&r?.price?+r.price/(g/1000):null}
function unit100g(r){let c=compPrice(r);if(c){if(/100\s*g/.test(c.per))return c.price;if(/kg/.test(c.per))return c.price/10;}let g=sizeGrams([r?.size,r?.product_name].filter(Boolean).join(' '));return g&&r?.price?+r.price/(g/100):null}
function unit100ml(r){let c=compPrice(r);if(c){if(/100\s*ml/.test(c.per))return c.price;if(/\bl\b/.test(c.per))return c.price/10;}let ml=sizeMl([r?.size,r?.product_name].filter(Boolean).join(' '));return ml&&r?.price?+r.price/(ml/100):null}
function unitEach(r){let c=compPrice(r);if(c&&(c.per.includes('each')||c.per.includes('ea')||c.per.includes('unit')))return c.price;let n=countUnits([r?.size,r?.product_name].filter(Boolean).join(' '));if(n&&r?.price)return +r.price/n;return r?.price?+r.price:null}
function unitMetric(id,r){if(UNIT100G.has(id)){let v=unit100g(r);return v?{value:v,label:'$/100 g'}:null}if(UNIT100ML.has(id)){let v=unit100ml(r);return v?{value:v,label:'$/100 mL'}:null}if(UNITEACH.has(id)){let v=unitEach(r);return v?{value:v,label:'$/each'}:null}return null}
function targetSizeOk(target,r){if(!target)return true;const t=clean(target),source=clean([r?.size,r?.product_name].filter(Boolean).join(' '));let m=t.match(/^([0-9.]+)(kg|g|ml|l)$/);if(m){const num=+m[1],unit=m[2];let targetBase=(unit==='kg'?num*1000:unit==='g'?num:unit==='l'?num*1000:num);let rx=unit==='kg'||unit==='g'?source.match(/([0-9.]+)\s*(kg|g)\b/):source.match(/([0-9.]+)\s*(l|ml)\b/);if(!rx)return true;let found=+rx[1],u=rx[2],foundBase=(u==='kg'?found*1000:u==='g'?found:u==='l'?found*1000:found);return Math.abs(foundBase-targetBase)/targetBase<=0.08;}m=t.match(/^([0-9]+)pack$/);if(m){let n=m[1];return source.includes(n+' pack')||source.includes(n+' ea')||source.includes(n+' count')||source.includes(n+' ct')||!/[0-9]+\s*(pack|ea|count|ct)\b/.test(source)}return true}
function acceptable(id,r,item){let n=clean(r?.product_name);if(!n||!targetSizeOk(item?.targetSize,r))return false;if((UNIT100G.has(id)||UNIT100ML.has(id)||UNITEACH.has(id))&&!item?.targetSize&&!unitMetric(id,r))return false;
  if(id==='bananas')return n.includes('banana')&&!n.includes('bread')&&!n.includes('loaf')&&!n.includes('cake')&&!n.includes('pepper');
  if(id==='grapes')return n.includes('grape')&&!n.includes('tomato'); if(id==='carrots')return n.includes('carrot');
  if(id==='chicken')return n.includes('chicken')&&n.includes('breast')&&n.includes('boneless')&&n.includes('skinless'); if(id==='pork')return n.includes('pork')&&n.includes('tenderloin');
  if(id==='eggwhites')return n.includes('egg')&&n.includes('white'); if(id==='vector')return n.includes('vector'); if(id==='ricekrispies')return n.includes('rice')&&n.includes('krisp');
  if(id==='milk')return n.includes('milk')&&n.includes('1%'); if(id==='eggs')return n.includes('egg')&&n.includes('large'); if(id==='wheatthins')return n.includes('wheat')&&n.includes('thin'); if(id==='ritz')return n.includes('ritz');
  if(id==='peanut')return n.includes('kraft')&&n.includes('peanut')&&n.includes('butter')&&n.includes('smooth'); if(id==='silk')return n.includes('silk')&&n.includes('hazelnut');
  if(id==='cheese')return n.includes('marble')&&n.includes('cheese')&&!n.includes('lactose free'); if(id==='bread')return n.includes('whole')&&n.includes('wheat')&&n.includes('bread'); if(id==='blueberries')return n.includes('blueberr');
  if(id==='potatoes')return n.includes('potato')&&(n.includes('baby')||n.includes('mini'))&&!n.includes('puree')&&!n.includes('food')&&!n.includes('snack')&&!n.includes('melties'); if(id==='clif')return n.includes('builder')&&n.includes('protein'); if(id==='kd')return (n.includes('kraft')&&n.includes('dinner'))||(n.includes('kraft')&&n.includes('macaroni')); if(id==='burgers')return (n.includes('beef')||n.includes('hamburger'))&&(n.includes('burger')||n.includes('patt'));
  return true}
async function vynn(id){const key=(process.env.VYNN_API_KEY||'').trim();if(!key)throw new Error('VYNN_API_KEY is not configured');const u='https://vynn.ai/v1/products/search?q='+encodeURIComponent(Q[id]||LABEL[id]||id)+'&province=AB&limit=40';const r=await fetch(u,{headers:{Authorization:'Bearer '+key}}),j=await r.json();if(!r.ok)throw new Error(j?.error?.message||('Vynn request failed for '+id));return j.results||[]}
function row(id,store,rec,item){if(!rec)return{id,label:item?.line||LABEL[id]||id,store,status:'unavailable',price:null,comparison_value:null,confidence:store==='Costco'?'unresolved':'regional proxy',notes:store==='Costco'?'No connected Costco price source yet':'No acceptable regional match'};let price=+rec.price,notes=[rec.product_name,rec.size].filter(Boolean).join(' · '),comparison_value=price;
  if(WEIGHTED.has(id)){let kg=unitKg(rec);if(!kg)return row(id,store,null,item);let target=item?.targetKg||1;price=kg*target;comparison_value=kg;notes+=' · comparison cost for '+target+' kg at $'+kg.toFixed(2)+'/kg'}
  else if(!item?.targetSize){let u=unitMetric(id,rec);if(u){comparison_value=u.value;notes+=' · '+u.label+' $'+u.value.toFixed(2)}}
  if(item?.mult&&item.mult>1){price*=item.mult;notes+=' · x'+item.mult}return{id,label:item?.line||LABEL[id]||id,store,status:'available',price,comparison_value,confidence:'regional proxy',notes}}
function localRow(id,store,item){let x=LOCAL[store]?.[id];if(!x)return null;return{id,label:item?.line||LABEL[id]||id,store,status:'available',price:x.price*(item?.mult||1),comparison_value:x.price,confidence:'local verified',notes:x.notes}}
function median(a){const x=[...a].sort((a,b)=>a-b);return x.length?x[Math.floor(x.length/2)]:null}
function applyRegionalOutliers(rows,altMap){let count=0;for(const id of [...new Set(rows.map(r=>r.id))]){const rr=rows.filter(r=>r.id===id&&r.status==='available'&&r.confidence!=='local verified'&&Number.isFinite(r.comparison_value));if(rr.length<3)continue;const med=median(rr.map(r=>r.comparison_value)),lo=med*0.60,hi=med*2.20;for(const r of rr){if(r.comparison_value<lo||r.comparison_value>hi){const alts=altMap.get(r.id+'|'+r.store)||[];let replaced=false;for(const alt of alts){const cand=row(r.id,r.store,alt,r.__item);if(cand.status==='available'&&Number.isFinite(cand.comparison_value)&&cand.comparison_value>=lo&&cand.comparison_value<=hi){r.price=cand.price;r.comparison_value=cand.comparison_value;r.notes=cand.notes+' · fallback candidate used after lower-priced outlier was rejected';replaced=true;break}}if(!replaced){r.status='unavailable';r.notes+=' · excluded as regional price outlier';r.price=null;count++}}}}return count}
function rankValue(id,r,item){if(WEIGHTED.has(id)){let v=unitKg(r);return Number.isFinite(v)?v:Infinity}if(item?.targetSize)return +r.price;let u=unitMetric(id,r);return u?u.value:+r.price} function candidatesFor(id,rs,bans,item){return rs.filter(r=>bans.some(b=>bannerOf(r).includes(b))&&acceptable(id,r,item)).sort((a,b)=>rankValue(id,a,item)-rankValue(id,b,item))}
function bestOneStore(rows,items){const stores=STORES.filter(s=>s!=='Costco');const eligible=items.filter(it=>rows.some(r=>r.id===it.id&&r.status==='available'));let best=null;for(const s of stores){const as=eligible.map(it=>rows.find(r=>r.id===it.id&&r.store===s&&r.status==='available')).filter(Boolean);if(!as.length)continue;const total=as.reduce((a,b)=>a+b.price,0);if(!best||as.length>best.assignments.length||(as.length===best.assignments.length&&total<best.total))best={store:s,assignments:as,total}}if(!best)return{status:'incomplete',priced_count:eligible.length,total_count:items.length};const local_count=best.assignments.filter(x=>x.confidence==='local verified').length;const missing=eligible.filter(it=>!best.assignments.some(a=>a.id===it.id)).map(it=>it.line||LABEL[it.id]||it.id);return{status:'complete',stores:[best.store],total:best.total,assignments:best.assignments,subtotals:{[best.store]:best.total},priced_count:eligible.length,total_count:items.length,partial:best.assignments.length<eligible.length,missing_at_store:missing,local_count,regional_count:best.assignments.length-local_count,local_pct:best.assignments.length?Math.round(100*local_count/best.assignments.length):0,estimated:true}}  function plan(rows,items,maxStores){const eligible=items.filter(it=>rows.some(r=>r.id===it.id&&r.status==='available'));let stores=STORES.filter(s=>s!=='Costco'),best=null,combos=[];for(let i=0;i<stores.length;i++){combos.push([stores[i]]);if(maxStores===2)for(let j=i+1;j<stores.length;j++)combos.push([stores[i],stores[j]])}
  for(const ss of combos){let as=[],subs={},ok=true;for(const it of eligible){let cands=rows.filter(r=>r.id===it.id&&r.status==='available'&&ss.includes(r.store)).sort((a,b)=>(a.comparison_value??a.price)-(b.comparison_value??b.price));if(!cands.length){ok=false;break}let c=cands[0];as.push(c);subs[c.store]=(subs[c.store]||0)+c.price}if(ok&&as.length){let total=Object.values(subs).reduce((a,b)=>a+b,0);if(!best||total<best.total)best={status:'complete',stores:ss,total,assignments:as,subtotals:subs}}}
  if(!best)return{status:'incomplete',priced_count:eligible.length,total_count:items.length};best.priced_count=eligible.length;best.total_count=items.length;best.partial=eligible.length<items.length;best.local_count=best.assignments.filter(x=>x.confidence==='local verified').length;best.regional_count=best.assignments.length-best.local_count;best.local_pct=Math.round(100*best.local_count/best.assignments.length);best.estimated=best.regional_count>0||best.partial;return best}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST required'});try{const items=Array.isArray(req.body?.items)?req.body.items:[];let rows=[],unresolved=[];const altMap=new Map();for(const it of items){for(const s of STORES){let lr=localRow(it.id,s,it);if(lr){lr.__item=it;rows.push(lr);continue}if(s==='Costco'){let r0=row(it.id,s,null,it);r0.__item=it;rows.push(r0);continue}}let rs=await vynn(it.id);for(const s of STORES.filter(x=>!['Superstore','No Frills','Costco'].includes(x))){let cands=candidatesFor(it.id,rs,BANNERS[s]||[],it);let rr=row(it.id,s,cands[0],it);rr.__item=it;if(cands.length>1)altMap.set(it.id+'|'+s,cands.slice(1,4));rows.push(rr)}for(const s of ['Superstore','No Frills'])if(!LOCAL[s]?.[it.id]){let cands=candidatesFor(it.id,rs,BANNERS[s]||[],it);let rr=row(it.id,s,cands[0],it);rr.__item=it;if(rr.status==='available')rr.confidence='regional fallback';if(cands.length>1)altMap.set(it.id+'|'+s,cands.slice(1,4));rows.push(rr)}}const anomaly_count=applyRegionalOutliers(rows,altMap);for(const r of rows)delete r.__item;for(const it of items)if(!rows.some(r=>r.id===it.id&&r.status==='available'))unresolved.push(it.line||LABEL[it.id]||it.id);const priced=items.filter(it=>rows.some(r=>r.id===it.id&&r.status==='available')).length;return res.status(200).json({rows,priced_count:priced,total_count:items.length,unresolved_items:unresolved,anomaly_count,best_one_store:bestOneStore(rows,items),best_two_store:plan(rows,items,2)});}catch(e){return res.status(500).json({error:e.message||'Comparison failed'})}}
