const STORES=['Superstore','No Frills','Walmart','Safeway','Sobeys','Costco'];
const BANNERS={Superstore:['real canadian superstore','superstore'],'No Frills':['no frills'],Walmart:['walmart'],Safeway:['safeway'],Sobeys:['sobeys']};
const LOCAL={
  Superstore:{milk:{price:6.35,notes:'Beatrice 1% 4L · Spruce Grove Superstore 1565'},eggs:{price:4.18,notes:'No Name large 12'},vector:{price:8.49,notes:'Kellogg’s Vector original'},bubly:{price:5.99,notes:'Bubly 12 pack'}},
  'No Frills':{milk:{price:6.35,notes:'Beatrice 1% 4L · Steve’s No Frills 3628'},eggs:{price:4.18,notes:'No Name large 12'},bubly:{price:6.50,notes:'Bubly 12 pack'}}
};
const Q={milk:'1% milk 4L',eggs:'large eggs 12',yogurt:'plain Greek yogurt 1 kg',eggwhites:'egg whites 500 g',vector:'Kelloggs Vector cereal 400 g',chicken:'boneless skinless chicken breast',bananas:'bananas',bubly:'Bubly 12 pack',wheatthins:'Wheat Thins Original',cheese:'marble cheese 400 g',bread:'whole wheat bread 675 g',romaine:'romaine hearts 3 pack',carrots:'carrots',peppers:'bell peppers 4 pack',oranges:'oranges',grapes:'grapes',potatoes:'baby potatoes',butter:'butter 454 g'};
const LABEL={milk:'1% milk 4L',eggs:'large eggs 12',yogurt:'plain Greek yogurt 1 kg',eggwhites:'egg whites 500 g',vector:'Vector cereal 400 g',chicken:'boneless skinless chicken breast',bananas:'bananas',bubly:'Bubly 12 pack',wheatthins:'Wheat Thins Original',cheese:'marble cheese 400 g',bread:'whole wheat bread 675 g',romaine:'romaine hearts 3 pack',carrots:'carrots',peppers:'bell peppers 4 pack',oranges:'oranges',grapes:'grapes',potatoes:'baby potatoes',butter:'butter 454 g'};
function clean(s){return String(s||'').toLowerCase().replace(/[^a-z0-9%]+/g,' ')}
function bannerOf(r){return clean(r?.banner?.value||r?.provider?.value||'')}
function sizeKg(s){s=clean(s);let m=s.match(/([0-9.]+)\s*kg/);if(m)return +m[1];m=s.match(/([0-9.]+)\s*g\b/);if(m)return +m[1]/1000;return null}
function unitKg(r){const c=r?.comparison_unit_price;if(c?.price&&c?.per){let p=+c.price,per=clean(c.per);if(per.includes('100g'))return p*10;if(per.includes('kg'))return p;}let kg=sizeKg(r?.size);return kg&&r?.price?+r.price/kg:null}
function targetSizeOk(target,r){if(!target)return true;const t=clean(target),source=clean([r?.size,r?.product_name].filter(Boolean).join(' '));let m=t.match(/^([0-9.]+)(kg|g|ml|l)$/);if(m){const num=+m[1],unit=m[2];let targetBase=(unit==='kg'?num*1000:unit==='g'?num:unit==='l'?num*1000:num);let rx=unit==='kg'||unit==='g'?source.match(/([0-9.]+)\s*(kg|g)\b/):source.match(/([0-9.]+)\s*(l|ml)\b/);if(!rx)return true;let found=+rx[1],u=rx[2];let foundBase=(u==='kg'?found*1000:u==='g'?found:u==='l'?found*1000:found);return Math.abs(foundBase-targetBase)/targetBase<=0.08;}m=t.match(/^([0-9]+)pack$/);if(m){let n=m[1];return source.includes(n+' pack')||source.includes(n+' ea')||source.includes(n+' count')||source.includes(n+' ct')||!/[0-9]+\s*(pack|ea|count|ct)\b/.test(source);}return true}
function acceptable(id,r,item){let n=clean(r?.product_name);if(!n)return false;if(!targetSizeOk(item?.targetSize,r))return false;if(id==='bananas')return n.includes('banana')&&!n.includes('bread')&&!n.includes('loaf')&&!n.includes('cake')&&!n.includes('pepper');if(id==='grapes')return n.includes('grape')&&!n.includes('tomato');if(id==='carrots')return n.includes('carrot');if(id==='chicken')return n.includes('chicken')&&n.includes('breast')&&n.includes('boneless')&&n.includes('skinless');if(id==='eggwhites')return n.includes('egg')&&n.includes('white');if(id==='vector')return n.includes('vector');if(id==='milk')return n.includes('milk')&&n.includes('1%');if(id==='eggs')return n.includes('egg')&&n.includes('large');if(id==='cheese')return n.includes('marble')&&n.includes('cheese')&&!n.includes('lactose free');if(id==='potatoes')return n.includes('potato')&&(n.includes('baby')||n.includes('mini'));return true}
async function vynn(id){const key=(process.env.VYNN_API_KEY||'').trim();if(!key)throw new Error('VYNN_API_KEY is not configured');const q=Q[id]||LABEL[id]||id;const u='https://vynn.ai/v1/products/search?q='+encodeURIComponent(q)+'&province=AB&limit=40';const r=await fetch(u,{headers:{Authorization:'Bearer '+key}});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||('Vynn request failed for '+id));return j.results||[]}
function row(id,store,rec,item){if(!rec)return{id,label:item?.line||LABEL[id]||id,store,status:'unavailable',price:null,confidence:store==='Costco'?'unresolved':'regional proxy',notes:store==='Costco'?'No connected Costco price source yet':'No acceptable regional match'};let price=+rec.price,notes=[rec.product_name,rec.size].filter(Boolean).join(' · ');if(['chicken','bananas','carrots','oranges','grapes'].includes(id)){let kg=unitKg(rec);if(!kg)return row(id,store,null,item);let target=item?.targetKg||1;price=kg*target;notes+=' · comparison cost for '+target+' kg at $'+kg.toFixed(2)+'/kg'}else if(item?.mult&&item.mult>1){price*=item.mult;notes+=' · x'+item.mult}return{id,label:item?.line||LABEL[id]||id,store,status:'available',price,confidence:'regional proxy',notes}}
function localRow(id,store,item){let x=LOCAL[store]?.[id];if(!x)return null;return{id,label:item?.line||LABEL[id]||id,store,status:'available',price:x.price*(item?.mult||1),confidence:'local verified',notes:x.notes}}
function median(a){const x=[...a].sort((a,b)=>a-b),n=x.length;return n?x[Math.floor(n/2)]:null}
function applyRegionalOutliers(rows){let count=0;for(const id of [...new Set(rows.map(r=>r.id))]){const rr=rows.filter(r=>r.id===id&&r.status==='available'&&r.confidence!=='local verified'&&Number.isFinite(r.price));if(rr.length<3)continue;const med=median(rr.map(r=>r.price));for(const r of rr){if(r.price<med*0.60||r.price>med*2.20){r.status='unavailable';r.notes+=' · excluded as regional price outlier';r.price=null;count++;}}}return count}
function plan(rows,items,maxStores){let stores=STORES.filter(s=>s!=='Costco'),best=null,combos=[];for(let i=0;i<stores.length;i++){combos.push([stores[i]]);if(maxStores===2)for(let j=i+1;j<stores.length;j++)combos.push([stores[i],stores[j]])}for(const ss of combos){let as=[],subs={},ok=true;for(const it of items){let cands=rows.filter(r=>r.id===it.id&&r.status==='available'&&ss.includes(r.store)).sort((a,b)=>a.price-b.price);if(!cands.length){ok=false;break}let c=cands[0];as.push(c);subs[c.store]=(subs[c.store]||0)+c.price}if(ok){let total=Object.values(subs).reduce((a,b)=>a+b,0);if(!best||total<best.total)best={status:'complete',stores:ss,total,assignments:as,subtotals:subs}}}if(!best)return{status:'incomplete'};best.local_count=best.assignments.filter(x=>x.confidence==='local verified').length;best.regional_count=best.assignments.length-best.local_count;best.local_pct=Math.round(100*best.local_count/best.assignments.length);best.estimated=best.regional_count>0;return best}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST required'});try{const items=Array.isArray(req.body?.items)?req.body.items:[];let rows=[],unresolved=[];for(const it of items){for(const s of STORES){let lr=localRow(it.id,s,it);if(lr){rows.push(lr);continue}if(s==='Costco'){rows.push(row(it.id,s,null,it));continue}}let rs=await vynn(it.id);for(const s of STORES.filter(x=>!['Superstore','No Frills','Costco'].includes(x))){let bans=BANNERS[s]||[];let cand=rs.filter(r=>bans.some(b=>bannerOf(r).includes(b))&&acceptable(it.id,r,it)).sort((a,b)=>(+a.price||1e9)-(+b.price||1e9))[0];rows.push(row(it.id,s,cand,it))}for(const s of ['Superstore','No Frills'])if(!LOCAL[s]?.[it.id]){let bans=BANNERS[s]||[];let cand=rs.filter(r=>bans.some(b=>bannerOf(r).includes(b))&&acceptable(it.id,r,it)).sort((a,b)=>(+a.price||1e9)-(+b.price||1e9))[0];let rr=row(it.id,s,cand,it);if(rr.status==='available')rr.confidence='regional fallback';rows.push(rr)}}const anomaly_count=applyRegionalOutliers(rows);for(const it of items)if(!rows.some(r=>r.id===it.id&&r.status==='available'))unresolved.push(it.line||LABEL[it.id]||it.id);let priced=items.filter(it=>rows.some(r=>r.id===it.id&&r.status==='available')).length;return res.status(200).json({rows,priced_count:priced,unresolved_items:unresolved,anomaly_count,best_one_store:plan(rows,items,1),best_two_store:plan(rows,items,2)});}catch(e){return res.status(500).json({error:e.message||'Comparison failed'})}}
